# Generated by Django 3.2.8 on 2021-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbiemovies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarbieMovies',
            new_name='BarbieMovie',
        ),
    ]
